[project]
name = "data-janitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
    "kaggle>=1.8.3",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
]
